version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ".:/app:rw"
      - "./data:/data:rw"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@database_default:5432/db
      DEBUG: 'True'
      SECRET_KEY: secret_key
      CSRF_TRUSTED_ORIGINS: https://localhost
    depends_on:
      - database_default
    networks:
      - what
    command: python manage.py runserver 0.0.0.0:80

  database_default:
    image: postgres:15.7-alpine
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      SERVICE_MANAGER: "fsm-postgres"
    volumes:
      - database-default:/var/lib/postgresql/data
      - ".:/app:rw"
    networks:
      - what

volumes:
  database-default:

networks:
  what: