version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
      - "50051:50051"
    env_file:
      - .env

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: pixsar
      POSTGRES_USER: pixsar
      POSTGRES_PASSWORD: namungoona
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
