services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: pixsar
      POSTGRES_PASSWORD: namungoona
      POSTGRES_DB: pixsar
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pixsar"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://pixsar:namungoona@db:5432/pixsar
      - CORS_ALLOWED_ORIGINS=http://localhost:3000