services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ".:/app:rw"
      - "./data:/data:rw"
    environment:
      - CORS_ALLOWED_ORIGINS=*
      - DATABASE_URL=postgres://huxaiphaeridris:%40HLl654321123@whatdb.postgres.database.azure.com:5432/postgres
      - SECRET_KEY=secret_key
      - DEBUG=False
      - CSRF_TRUSTED_ORIGINS=https://whatbackend.us.aldryn.io
    links:
      - "database_default"
    command: python manage.py runserver 0.0.0.0:80

  database_default:
    image: postgres:15.7-alpine
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ".:/app:rw"
      - "database-default:/var/lib/postgresql/data/"

volumes:
  database-default:
