version: "2.4"

services:
  web:
    build: "."
    ports:
      - "8000:80"
    volumes:
      - ".:/app:rw"
      - "./data:/data:rw"
    env_file: .env
    command: python manage.py runserver 0.0.0.0:80
    links:
      - "database_default"

  database_default:
    image: postgres:13.5-alpine
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
    volumes:
      - "./data/db:/var/lib/postgresql/data/"

volumes:
  data:
